CREATE TABLE `product` (
  `id` int(10) NOT NULL AUTO_INCREMENT,
  `product_name` varchar(100) DEFAULT NULL COMMENT ''推广商品名称'',
  `logo` varchar(1000) DEFAULT NULL COMMENT ''商品logo'',
  `product_type` int(10) DEFAULT NULL COMMENT ''1-信用卡，2贷款'',
  `is_hot` int(2) DEFAULT ''0'' COMMENT ''0-非热门，1-热们'',
  `is_show` int(2) DEFAULT ''0'' COMMENT ''0-不展示，1-展示'',
  `customer` int(10) DEFAULT NULL COMMENT ''广告主id'',
  `is_ in_shop` int(2) DEFAULT ''0'' COMMENT ''是否在店铺'',
  `is_shelf` int(2) DEFAULT ''0'' COMMENT ''是否上架'',
  `create_time` timestamp NULL DEFAULT NULL,
  `modify_time` timestamp NULL DEFAULT NULL,
  `commission` decimal(19,2) DEFAULT NULL COMMENT ''佣金'',
  `sort_val` int(10) DEFAULT NULL COMMENT ''排序值'',
  `bg_category` varchar(10) DEFAULT NULL COMMENT ''后台分类，多个逗号分隔'',
  `amount_line` int(10) DEFAULT NULL COMMENT ''贷款最高额度上限'',
  `progress_query_img` varchar(1000) DEFAULT NULL COMMENT ''信用卡进度查询图(多个逗号分隔)'',
  `allow_rate` decimal(5,2) DEFAULT NULL COMMENT ''通过率'',
  `apply_num` int(10) DEFAULT NULL COMMENT ''申请人数'',
  `apply_condition` varchar(200) DEFAULT NULL COMMENT ''申请条件'',
  `apply_tp_img` varchar(1000) DEFAULT NULL COMMENT ''贷款申请流程图片'',
  `day_rate` decimal(5,2) DEFAULT NULL COMMENT ''日利率'',
  `month_rate` decimal(5,2) DEFAULT NULL COMMENT ''月利率'',
  `a_begin` int(10) DEFAULT NULL COMMENT ''A阶段起始值'',
  `a_limit` int(10) DEFAULT NULL COMMENT ''A阶段上限值'',
  `b_begin` int(10) DEFAULT NULL,
  `b_limit` int(10) DEFAULT NULL,
  `c_start` int(10) DEFAULT NULL,
  `c_limit` varchar(100) DEFAULT NULL,
  `a_level_reward` decimal(5,2) DEFAULT NULL COMMENT ''A阶段奖励'',
  `b_level_reward` decimal(5,2) DEFAULT NULL,
  `c_level_reward` decimal(5,2) DEFAULT NULL,
  `base_salary` decimal(5,2) DEFAULT NULL COMMENT ''基本工资'',
  `month_salary` varchar(100) DEFAULT NULL COMMENT ''月工资'',
  `salary` varchar(100) DEFAULT NULL COMMENT ''工资'',
  `salary_desc` varchar(500) DEFAULT NULL COMMENT ''工资描述'',
  `month_salary_desc` varchar(500) DEFAULT NULL COMMENT ''月工资描述'',
  `second_summary` varchar(500) DEFAULT NULL COMMENT ''二级汇总'',
  `third_summary` varchar(500) DEFAULT NULL COMMENT ''三级汇总'',
  `detail_header_img` varchar(1000) DEFAULT NULL COMMENT ''详情页头部图片'',
  `card_long_img` varchar(1000) DEFAULT NULL COMMENT ''信用卡长图'',
  `product_show_img` varchar(1000) DEFAULT NULL COMMENT ''产品展示图'',
  `burundian` varchar(10) DEFAULT NULL COMMENT ''产品利润点'',
  `settlement_type` int(2) DEFAULT NULL COMMENT ''结算类型显示 1：实时结/2：T+1结/3：T+2结/4：T+3结/5：每周一结/6：每周二结/7：每周三结/8：每周四结/9：每周五结/10：次月5-15日结/11：次月20-25结'',
  `expire_unit` varchar(255) DEFAULT NULL COMMENT ''期限单位'',
  `how_settle` varchar(255) DEFAULT NULL COMMENT ''如何结算奖金'',
  `expire_begin` int(10) DEFAULT NULL COMMENT ''期限开始'',
  `expire_end` int(10) DEFAULT NULL COMMENT ''期限结束'',
  `commission_standard` varchar(100) DEFAULT NULL COMMENT ''返佣标准'',
  `share_title` varchar(200) DEFAULT NULL COMMENT ''分享内容-标题'',
  `card_progress_img` varchar(0) DEFAULT NULL COMMENT ''办卡流程图'',
  `base_right` varchar(200) DEFAULT NULL COMMENT ''基本权益'',
  `preferential` varchar(200) DEFAULT NULL COMMENT ''优惠活动'',
  `special_tag` varchar(200) DEFAULT NULL COMMENT ''特殊标签'',
  `special_txt` varchar(255) DEFAULT NULL COMMENT ''特色文案'',
  `unit` varchar(255) DEFAULT NULL COMMENT ''阶梯单位'',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4;

